format = """
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$directory\
$shlvl\
$vcsh\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$crystal\
$kubernetes\
$env_var\
$custom\
$cmd_duration\
[ÓÇ∞](bright-white)\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

command_timeout = 1000

[directory]
truncation_length = 8
truncation_symbol = "‚Ä¶/"
format="[ $path]($style)[$read_only]($read_only_style)[ ]($style)"
style = "bold black bg:bright-blue"

[gcloud]
format = '[$symbol$account(\($project\))]($style)  ÓÇ∞'
disabled = true

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bold bg:93"

[git_status]
format = '([ $ahead_behind$all_status ]($style))'
ahead = "‚á°${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count} "
staged = "+${count} "
untracked = "?${count} "
conflicted = "‚ö†${count} "
stashed = "‚Ü™${count} "
# stashed = "Ôöê${count} "
modified = "‚úé${count} "
renamed	= "‚éÅ${count} "
deleted	= "‚úò${count} "
style = "bold white bg:red"

[kubernetes]
disabled = false
format = '[ $symbol](bold bg:21)[$context]($style)[( $namespace) ]($style dimmed)'
symbol = "‚éà "
style = "bold white bg:21"
[kubernetes.context_aliases]
"nuk.rgielen.com" = "nuk"
"docker-desktop" = "üê≥"
"microk8s" = "¬µk8s"
"gke_.*-(?P<cluster>[\\w-]+)" = "gke-$cluster"

[java]
format = "[ ${symbol}(${version} )]($style)"
symbol = "‚òï"
style = "bold 1 bg:bright-white"
version_format = "${major}"

[package]
format = "[$symbol$version ]($style)"
style = "bold bg:208"

[env_var.KUBECONFIG]
format = "[ $symbol $env_value ]($style)"
symbol="‚öô"
style = "bold yellow bg:21"

[username]
style_user = "red bg:bright-yellow"
style_root = "black bold bg:red"
format = "[$user@]($style)"
show_always = false

[hostname]
ssh_only = true
format =  "[$hostname]($style)"
style = "black bold bg:bright-yellow"
trim_at = "."

[cmd_duration]
format = "[ ‚ó∑ $duration ]($style)"
style = "red bg:229"
show_milliseconds = true

[status]
format = "[ $symbol $status ]($style)"
disabled = false
style = "bold white bg:red"
map_symbol = true
